[package]
name = "testing"
version = "1.0.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]


[dependencies]
cw20 = { version = "0.8" }
terra-cosmwasm = { version = "2.2.0" }
cosmwasm-std = { version = "0.16.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = "0.9.1"
cw-storage-plus = {version = "0.8.0", features = ['iterator']}
cw-asset = "0.3.4"

[dev-dependencies]
cosmwasm-schema = "0.16.0"